# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  lane :firebase do 
    firebase_app_distribution(
	  app: ENV["firebase_app_id"],
	  firebase_cli_token: ENV["firebase_refresh_token"],
	  apk_path: ENV["fastlane_apk_distribution_path"],
	  release_notes: "Deploy feito via - #{ENV["ci_provider"]}",
	  testers: ENV["meu_email"]
	)
  end
end
